name: stak-notebooks
channels:
  - http://ssb.stsci.edu/astroconda
  - conda-forge
dependencies:
  - python==2.7
  - numpy
  - scipy
  - astropy
  - numpydoc
  - nbconvert>=5.0.0
  - sphinx>=1.5
  - ipython
  - jupyter
  - pip:
    - sphinx_rtd_theme
    - stsci_rtd_theme
